spring:
  application:
    name: cxygzl-core-app
  datasource:
    url: jdbc:mysql://localhost:3307/simple_flow?allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    ##redis地址
    host: localhost
    ##redis端口
    port: 6379
    ##使用的db
    database: 13
    password: 123456
server:
  port: 26858

logging:
  config: classpath:logback.xml

node:
  data:
    store: remoteDateStore
biz:
  url: http://127.0.0.1:26859

#  不需要表单引擎 idm引擎
flowable:
  common:
    app:
      idm-url: /a.html
      idm-admin:
        user: a
        password: a
  form:
    enabled: false
  idm:
    enabled: false
