spring:
  datasource:
    url: jdbc:mysql://myserver:3306/cxygzl_core_dd?allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SD342Jf632JD^123
  redis:
    host: myserver
    port: 6379
    database: 13

logging:
  config: classpath:logback-dd-pro.xml


server:
  port: 26868

biz:
  url: http://127.0.0.1:26869
