spring:
  redis:
    host: myserver
    port: 6379
    database: 13
  datasource:
    url: jdbc:mysql://localhost:3306/cxygzl_biz?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SD342Jf632JD^123


logging:
  config: classpath:logback-pro.xml



file:
  dir: /home/cxygzl/static
  showUrl: http://gzldemo.ittool.cc/wj/


sa-token:
  # token名称 (同时也是cookie名称)
  token-name: cxygzl
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true


