rename table process_copy to process_instance_copy;
rename table process_execution to process_instance_execution;
rename table process_node_record to process_instance_node_record;
rename table process_node_record_assign_user to process_instance_assign_user_record;
